### ISSUE TITLE
Additional Mod Incompatibilities

### ISSUE THREAD

**Issue by Michael-McKinley** [PFQNiet/Satisfactorio#96]
Thank you for this mod - I am excited to try it.

I had a few other mods in my typical mods list that had conflicts with Satisfactorio, and I thought I would list them here so you could decide if you wanted to add them to your mod's "Incompatible" list. Most of these do not fit the thematic idea of Satisfactory ... so I am **_not_** requesting there be any changes to your mod to allow them to work.

Advanced Solar High Resolution		0.6.10
Afraid Of The Dark (enforced personal lights + more) 1.1.1
Belt Balancer (Improved Performance)	3.1.3
Big Brother						0.5.4
Big Mning Drill					0.1.1
Black Rubber Belts					1.0.3
Cheese's Concentrated Solar			0.3.2
Loader Redux						1.8.1
LTN - Logistic Train network			1.18.3
Shuttle Train Continued				1.1.0
Transport Drones					1.0.14
Wire Shortcuts					1.1.13

**Comment by PFQNiet** [comment]
Because Satisfactorio makes such fundamental changes to the very core of Factorio, very few mods will actually work. Listing every incompatible mod would be a very long list! It would be best to assume that all mods are incompatible unless listed in the Optional Dependencies - those are mods that have been tested and/or have had compatibility patches added. If there is a particular mod you would like me to look into making compatible then I'm happy to hear suggestions.
